apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: t05-fluentd
  namespace: fluent
  labels:
    k8s-app: t05-fluentd
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: t05-fluentd
      version: v1
  template:
    metadata:
      labels:
        k8s-app: t05-fluentd
        version: v1
    spec:
      serviceAccount: t05-fluentd
      serviceAccountName: t05-fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: t05-fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        ports:
        - containerPort: 24224
          protocol: TCP
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "t05-elasticsearch"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: t05-fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: t05-fluentd-config
        configMap:
          name: t05-fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t05-fluentd
  namespace: fluent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: t05-fluentd
  namespace: fluent
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: t05-fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: t05-fluentd
subjects:
- kind: ServiceAccount
  name: t05-fluentd
  namespace: fluent
