apiVersion: apps/v1
kind: Deployment
metadata:
  name: t05-api
  labels:
    app: t05-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-api
  template:
    metadata:
      labels:
        app: t05-api
    spec:
      containers:
      - name: t05-api
        image: gitlab.sdu.dk:5050/semester-project-e2021/team-05/template/docker/api
        ports:
        - containerPort: 5000
        resources:
          limits:
              cpu: 150m
              memory: 100Mi
          requests:
              cpu: 50m
              memory: 50Mi
      imagePullSecrets:
      - name: sdugitlab

--- 
apiVersion: v1
kind: Service
metadata:
  name: service01
spec: 
  type: ClusterIP
  selector:
    app: t05-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
