apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: t05-es-cluster
spec:
  serviceName: t05-elasticsearch
  replicas: 3 #change this for more pod instances
  selector:
    matchLabels:
      app: t05-elasticsearch
  template:
    metadata:
      labels:
        app: t05-elasticsearch
    spec:
      containers:
      - name: t05-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
        resources:
          limits:
              cpu: 400m
              memory: 1100Mi
          requests:
              cpu: 200m
              memory: 500Mi
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: t05-elasticsearch
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "t05-es-cluster-0.t05-elasticsearch,t05-es-cluster-1.t05-elasticsearch,t05-es-cluster-2.t05-elasticsearch"
          - name: cluster.initial_master_nodes
            value: "t05-es-cluster-0,t05-es-cluster-1,t05-es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: t05-elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ] #storage class will give an error if not set on kubernetes cluster
      storageClassName: longhorn # Storage class currently unknown, using default
      resources:
        requests:
          storage: 2Gi #change this for more persistence storage. Was 100Gi before.

---
kind: Service
apiVersion: v1
metadata:
  name: t05-elasticsearch
  labels:
    app: t05-elasticsearch
spec:
  selector:
    app: t05-elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node